### Cadastrar
POST http://localhost:5000/api/pessoa/cadastrar
Content-Type: application/json


{
	"nome": "Ana Souza",
	"altura": 1.70,
	"peso": 65
}

### Listar Pessoas
GET http://localhost:5000/api/pessoa/listar
