// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251126212019_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("API.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            CriadoEm = new DateTime(2025, 11, 26, 18, 20, 19, 743, DateTimeKind.Local).AddTicks(5948),
                            Nome = "Trabalho"
                        },
                        new
                        {
                            CategoriaId = 2,
                            CriadoEm = new DateTime(2025, 11, 26, 18, 20, 19, 743, DateTimeKind.Local).AddTicks(5949),
                            Nome = "Estudos"
                        },
                        new
                        {
                            CategoriaId = 3,
                            CriadoEm = new DateTime(2025, 11, 26, 18, 20, 19, 743, DateTimeKind.Local).AddTicks(5950),
                            Nome = "Lazer"
                        });
                });

            modelBuilder.Entity("API.Models.Tarefa", b =>
                {
                    b.Property<string>("TarefaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("TarefaId");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            TarefaId = "6a8b3e4d-5e4e-4f7e-bdc9-9181e456ad0e",
                            CategoriaId = 1,
                            CriadoEm = new DateTime(2025, 12, 3, 18, 20, 19, 743, DateTimeKind.Local).AddTicks(6118),
                            Status = "Não iniciada",
                            Titulo = "Concluir relatório"
                        },
                        new
                        {
                            TarefaId = "2f1b7dc1-3b9a-4e1a-a389-7f5d2f1c8f3e",
                            CategoriaId = 2,
                            CriadoEm = new DateTime(2025, 11, 29, 18, 20, 19, 743, DateTimeKind.Local).AddTicks(6132),
                            Status = "Não iniciada",
                            Titulo = "Estudar Angular"
                        },
                        new
                        {
                            TarefaId = "e5d4a7b9-1f9e-4c4a-ae3b-5b7c1a9d2e3f",
                            CategoriaId = 3,
                            CriadoEm = new DateTime(2025, 12, 10, 18, 20, 19, 743, DateTimeKind.Local).AddTicks(6135),
                            Status = "Não iniciada",
                            Titulo = "Passeio no parque"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
